// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Finanzas.Test.Integration.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DistribuciNDetalladaSplitsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Distribuci�n Detallada (Splits)", "  Como usuario quiero desglosar un movimiento en varias categor�as\r\n  Para saber " +
                "exactamente en qu� gasto mi dinero", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "TransactionSplits.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/TransactionSplits.feature.ndjson", 7);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Gasto multi-categor�a exitoso en una sola compra")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Gasto multi-categor�a exitoso en una sola compra")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Distribuci�n Detallada (Splits)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unitary")]
        public async global::System.Threading.Tasks.Task GastoMulti_CategorAExitosoEnUnaSolaCompra()
        {
            string[] tagsOfScenario = new string[] {
                    "Unitary"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Gasto multi-categor�a exitoso en una sola compra", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("una cuenta \"Efectivo\" con 500 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("registro un movimiento de 100 \"USD\" llamado \"Supermercado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Categor�a",
                            "Monto"});
                table15.AddRow(new string[] {
                            "Alimentos",
                            "70"});
                table15.AddRow(new string[] {
                            "Limpieza",
                            "30"});
#line 10
    await testRunner.AndAsync("distribuyo el gasto en los siguientes splits:", ((string)(null)), table15, "Y ");
#line hidden
#line 14
    await testRunner.ThenAsync("el saldo de \"Efectivo\" debe ser 400 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 15
    await testRunner.AndAsync("el movimiento debe tener 2 distribuciones registradas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 16
    await testRunner.AndAsync("el monto total de los splits debe ser igual a 100 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Error al intentar distribuir un monto diferente al total del movimiento")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Error al intentar distribuir un monto diferente al total del movimiento")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Distribuci�n Detallada (Splits)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unitary")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Validation")]
        public async global::System.Threading.Tasks.Task ErrorAlIntentarDistribuirUnMontoDiferenteAlTotalDelMovimiento()
        {
            string[] tagsOfScenario = new string[] {
                    "Unitary",
                    "Validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Error al intentar distribuir un monto diferente al total del movimiento", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("un movimiento de 100 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Categor�a",
                            "Monto"});
                table16.AddRow(new string[] {
                            "Alimentos",
                            "50"});
                table16.AddRow(new string[] {
                            "Limpieza",
                            "40"});
#line 21
    await testRunner.WhenAsync("intento distribuir el gasto en:", ((string)(null)), table16, "Cuando ");
#line hidden
#line 25
    await testRunner.ThenAsync("el sistema debe rechazar la operaci�n con el mensaje \"La suma de los splits debe " +
                        "ser igual al total del movimiento\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Impedir splits con montos negativos o cero")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Impedir splits con montos negativos o cero")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Distribuci�n Detallada (Splits)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unitary")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Validation")]
        public async global::System.Threading.Tasks.Task ImpedirSplitsConMontosNegativosOCero()
        {
            string[] tagsOfScenario = new string[] {
                    "Unitary",
                    "Validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Impedir splits con montos negativos o cero", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.GivenAsync("un movimiento de 100 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Categor�a",
                            "Monto"});
                table17.AddRow(new string[] {
                            "Alimentos",
                            "-10"});
                table17.AddRow(new string[] {
                            "Limpieza",
                            "110"});
#line 30
    await testRunner.WhenAsync("intento distribuir el gasto en:", ((string)(null)), table17, "Cuando ");
#line hidden
#line 34
    await testRunner.ThenAsync("el sistema debe rechazar la operaci�n con el mensaje \"El monto de cada distribuci" +
                        "�n debe ser mayor a cero\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Categorizaci�n parcial de un movimiento")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Categorizaci�n parcial de un movimiento")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Distribuci�n Detallada (Splits)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unitary")]
        public async global::System.Threading.Tasks.Task CategorizaciNParcialDeUnMovimiento()
        {
            string[] tagsOfScenario = new string[] {
                    "Unitary"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Categorizaci�n parcial de un movimiento", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.WhenAsync("registro un movimiento de 100 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 39
    await testRunner.AndAsync("solo asigno 60 \"USD\" a la categor�a \"Salud\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 40
    await testRunner.ThenAsync("el sistema debe asignar autom�ticamente 40 \"USD\" a la categor�a \"Sin Clasificar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 41
    await testRunner.AndAsync("el movimiento debe estar marcado como \"Distribuci�n Incompleta\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Impedir asignar splits a una categor�a inexistente")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Impedir asignar splits a una categor�a inexistente")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Distribuci�n Detallada (Splits)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unitary")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Validation")]
        public async global::System.Threading.Tasks.Task ImpedirAsignarSplitsAUnaCategorAInexistente()
        {
            string[] tagsOfScenario = new string[] {
                    "Unitary",
                    "Validation"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Impedir asignar splits a una categor�a inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
    await testRunner.GivenAsync("un movimiento de 100 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 46
    await testRunner.WhenAsync("intento asignar 100 \"USD\" a una categor�a que no existe", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 47
    await testRunner.ThenAsync("el sistema debe rechazar la operaci�n con el mensaje \"La categor�a especificada n" +
                        "o existe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
