// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Finanzas.Test.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ConsultasEInformesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Consultas e Informes", "  Como usuario quiero ver el estado global de mis finanzas\r\n  Para tomar mejores " +
                "decisiones econ�micas basado en datos reales", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Reporting.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Reporting.feature.ndjson", 3);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Visualizar resumen de gastos por categor�a basado en splits")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Visualizar resumen de gastos por categor�a basado en splits")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Consultas e Informes")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Reporting")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ReadOnly")]
        public async global::System.Threading.Tasks.Task VisualizarResumenDeGastosPorCategorABasadoEnSplits()
        {
            string[] tagsOfScenario = new string[] {
                    "Reporting",
                    "ReadOnly"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar resumen de gastos por categor�a basado en splits", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Nombre",
                            "Saldo Inicial",
                            "Moneda"});
                table9.AddRow(new string[] {
                            "Banco",
                            "1500",
                            "USD"});
                table9.AddRow(new string[] {
                            "Efectivo",
                            "500",
                            "USD"});
#line 8
    await testRunner.GivenAsync("las siguientes cuentas configuradas:", ((string)(null)), table9, "Dado ");
#line hidden
#line 12
    await testRunner.AndAsync("las siguientes categor�as: \"Comida, Transporte, Limpieza\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Descripci�n",
                            "Cuenta",
                            "Monto Total"});
                table10.AddRow(new string[] {
                            "Supermercado",
                            "Banco",
                            "200"});
                table10.AddRow(new string[] {
                            "Gasolinera",
                            "Efectivo",
                            "50"});
#line 13
    await testRunner.AndAsync("se han registrado los siguientes movimientos:", ((string)(null)), table10, "Y ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Categor�a",
                            "Monto"});
                table11.AddRow(new string[] {
                            "Comida",
                            "150"});
                table11.AddRow(new string[] {
                            "Limpieza",
                            "50"});
#line 17
    await testRunner.AndAsync("el movimiento \"Supermercado\" se distribuy� en:", ((string)(null)), table11, "Y ");
#line hidden
#line 21
    await testRunner.WhenAsync("consulto el \"Resumen de Gastos por Categor�a\" del mes actual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Categor�a",
                            "Total Gastado"});
                table12.AddRow(new string[] {
                            "Comida",
                            "150"});
                table12.AddRow(new string[] {
                            "Limpieza",
                            "50"});
                table12.AddRow(new string[] {
                            "Transporte",
                            "0"});
#line 22
    await testRunner.ThenAsync("el reporte debe mostrar los siguientes totales:", ((string)(null)), table12, "Entonces ");
#line hidden
#line 27
    await testRunner.AndAsync("el Patrimonio Neto total debe ser 1750 \"USD\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
